# This is a basic workflow to help you get started with Actions
name: Continuous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    - jenk
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: my_first_job
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: set up JDK 17
        run: echo Hello, world!
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # Runs a set of commands using the runners shell
      - name: Show Java version
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

        run: "java -version"

        - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: jenk
          
      - name: show directory
      run: 'pwd' 

      - name: list files
      run: 'ls -al'

      - name: install dependencies
      run: 'mvn compile'

      - name: Build application
      run: 'mvn packeg -Dskiptests'

      - name: Test application
      run: 'mvn test'
